version: '3.1'
services:
  web:
    build:
      context: ./docker
    volumes:
      - ./www:/var/www
    ports:
      - "80:80"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:9.6.1
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: palindromes
